version: "3.7"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5002:80 # web interface
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
